name: Build and publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'  # 태그가 vX.X.X 형식일 때만 실행
  workflow_dispatch: # This line allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

#      - name: Test
#        run: dotnet test --no-restore --verbosity normal

      - name: Copy DLL and PDB to Unity package
        run: |
          cp -f DateTimeTypes/bin/Release/netstandard2.1/*.dll UnityPackages/DateTimeTypes/Runtime/
          cp -f DateTimeTypes/bin/Release/netstandard2.1/*.pdb UnityPackages/DateTimeTypes/Runtime/
          cp -f DateTimeTypes.NewtonsoftJson/bin/Release/netstandard2.1/*.dll UnityPackages/DateTimeTypes.NewtonsoftJson/Runtime/
          cp -f DateTimeTypes.NewtonsoftJson/bin/Release/netstandard2.1/*.pdb UnityPackages/DateTimeTypes.NewtonsoftJson/Runtime/

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add UnityPackages/DateTimeTypes/package.json
          git add UnityPackages/DateTimeTypes/Runtime/
          git add UnityPackages/DateTimeTypes.NewtonsoftJson/package.json
          git add UnityPackages/DateTimeTypes.NewtonsoftJson/Runtime/
          git diff --staged --quiet || git commit -m "Update Unity package binaries" || echo "No changes to commit"
          git push
          
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkgs

      - name: Publish the package
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
